[package]
name = "smafa"
version = "0.3.0"
license = "GPL-3.0"
description = "Biological sequence aligner for aligned sequences."
homepage = "https://github.com/wwood/smafa"
repository = "https://github.com/wwood/smafa"
documentation = "https://github.com/wwood/smafa"
readme = "README.md"
authors = ["Ben Woodcroft <donttrustben@gmail.com>"]

[dependencies]
bio = "^0.22"
log = "^0.3.8"
env_logger = "^0.4.3"
clap = "^2.32.0"
serde = "^1.0.73"
bincode = "^0.8.0"
serde_derive = "^1.0.73"
snap = "^0.2.4"

[dev-dependencies]
tempfile = "^2.1.6"

[features]
unstable = []
