[package]
name = "smafa"
version = "0.1.0"
authors = ["Ben Woodcroft <donttrustben@gmail.com>"]

[dependencies]
#bio = "=0.14.*"
bio = {git = "https://github.com/rust-bio/rust-bio"}
log = "0.3.*"
env_logger = "0.4.*"
clap = "2.26.*"