[package]
name = "smafa"
version = "0.1.0"
authors = ["Ben Woodcroft <donttrustben@gmail.com>"]

[dependencies]
#bio = "0.14.*"
#bio = {git = "file:///home/ben/git/rust-bio"}
bio = {git = "https://github.com/rust-bio/rust-bio"}
log = "0.3.*"
env_logger = "0.4.*"
clap = "2.26.*"
serde = "1.0.*"
serde_json = "1.0.*"
bincode = "0.8.*"
serde_derive = "1.0.*"
